@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

class Creator {
    +genericOper1()
    +genericOper2()
    createProduct()
}
note top of Creator
    genericOpers calls createProduct
end note


interface Product {
    doStuff()
}

class ConcreteProductA {
    doStuff()
}

class ConcreteProductB {
    doStuff()
}


Product <|.. ConcreteProductA
Product <|.. ConcreteProductB

Creator .> Product
class ConcreteCreatorA {
   createProduct()
}

class ConcreteCreatorB {
   createProduct()
}

Creator <|-- ConcreteCreatorA
Creator <|-- ConcreteCreatorB
Client -> Creator : createProduct()


@enduml